version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conexa-api
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=conexa
    networks:
      - conexa-network

  postgres:
    image: postgres:15-alpine
    container_name: conexa-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=conexa
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - conexa-network

networks:
  conexa-network:
    driver: bridge

volumes:
  postgres-data: